name: Clojure CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install npm dependencies
      run: npm install
    - name: Install Clojure dependencies
      run: lein deps
    - name: Run tests
      run: lein kaocha
